---
- job:
    name: tox-flake8
    parent: tox
    description: |
      Run flake8 tests
    vars:
      tox_envlist: flake8

- job:
    name: tox-integration-podman
    parent: tox
    description: |
      Run podman-based integration tests
    pre-run: .zuul/playbooks/pre-podman.yaml
    vars:
      tox_envlist: integration_podman

- project:
    name: github.com/release-depot/patch_rebaser
    github-check:
      jobs:
        - tox-py27:
            nodeset: rdo-centos-7
        - tox-py36:
            nodeset: rdo-centos-8
        - tox-py37:
            nodeset: single-fedora-31-node
        - tox-flake8:
            nodeset: rdo-centos-8
        - tox-integration-podman:
            nodeset: single-fedora-31-node
